### ISSUE TITLE
"and export this var its path."

### ISSUE THREAD

**Issue by Martin324923** [mitchweaver/subs#1]
Hello Mitch,
step by step I'm getting rid of my google account and I was just today thinking about how to keep my Youtube subscriptions. Then someone posted your program on the /r/degoogle subreddit. This is exactly what I'm looking for, so thank you a lot for this.
However, I don't understand the following sentence:

"Create your $SUBS_FILE, as described below, and export this var its path."

This is probably a stupid question, but what do you mean by "export this var its path"? Is it enough if I change the directory (~/files/subs.txt) in subs or do have to do anything else? 
Thanks again!
Cheers,
Martin

**Comment by mitchweaver** [comment]
Ah, perhaps this should be more clear. 

Having a variable "exported" is jargon for having it in the environment.  
Add this to your `~/.profile`
```
export SUBS_FILE=/path/to/your/subs.txt
```

**Comment by Martin324923** [comment]
Thanks, now it works.
What distribution are you using in your example image? I have a problem that the menu isn't displayed in the current terminal window but instead on the whole screen, "windowid 0" so to speak. Did you have any issues in this regard?

Irrespective of this, I put 
export SUBS_MENU_PROG='dmenu -b -l 12 -p Subs:'
in my ~/.profile as a workaround and it works great!

**Comment by mitchweaver** [comment]
@Martin324923 I'm using Void, but it really doesn't matter which distribution.

Also you can customize the look of the menu with different patches, I use quite a few. Can see them in my [suckless](http://github.com/mitchweaver/suckless) repo.

Alternatively a lot of people like `rofi` over dmenu

**Comment by Martin324923** [comment]
Yessss, I installed rofi and now it's perfect. Now Youtube is crossed from my list. :-)
